version: '3.4'

volumes:
    data-volume:
    elasticsearch-volume:

networks:
    my-proxy-net:
        external:
            name: tagwalk

services:
    db:
        image: mariadb:10.0
        command: --max_allowed_packet=64M
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - data-volume:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d/
        ports:
            - 3306:3306
        networks:
            - my-proxy-net
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        environment:
            COMPOSER_ALLOW_SUPERUSER: 1
        volumes:
            - ${BACK_APP_PATH}:/var/www/tagwalk-admin
            - ${FRONT_APP_PATH}:/var/www/tagwalk-www
            - ./logs/symfony/admin:/var/www/tagwalk-admin/app/logs
            - ./logs/symfony/www:/var/www/tagwalk-www/app/logs
            - ./php7-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ../uploads:/var/www/tagwalk-admin/uploads
        ports:
            - 9000
        networks:
            - my-proxy-net
    nginx:
        build: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ${BACK_APP_PATH}:/var/www/tagwalk-admin:rw
            - ${FRONT_APP_PATH}:/var/www/tagwalk-www
            - ../uploads:/var/www/tagwalk-admin/uploads
            - ./logs/nginx/:/var/log/nginx
            - ./nginx/certs:/etc/nginx/ssl
        depends_on: [ php ]
        networks:
            - my-proxy-net
    elk:
        build: elk
        ports:
            - 5601:5601
            - 9200:9200
            - 5044:5044
        volumes:
            - ./elk/logstash/patterns:/opt/logstash/patterns
            - ./elk/logstash/driver:/opt/logstash/driver
            - ./elk/logstash/conf:/etc/logstash/conf.d
            - elasticsearch-volume:/var/data/elasticsearch
            - ./logs/nginx/:/var/log/nginx
            - ./logs/symfony/admin:/var/www/tagwalk-admin/app/logs
            - ./logs/symfony/www:/var/www/tagwalk-www/app/logs
        depends_on: [ db ]
        networks:
            - my-proxy-net
    ftpd:
        build: proftpd
        ports:
            - 20:20
            - 21:21
        volumes:
          - ../uploads:/home/ftp/uploads
        privileged: true
        networks:
            - my-proxy-net
